{"Title": "TIGER RUNNER", "Onsale": "New", "Price": "$70.00", "Width": "Standard", "Product Category": "Men's Sportstyle Shoes", "Current Color": "White/French Blue", "Deal link": "", "Coming soon?": "\n        TIGER RUNNER\n    ", "Image link": "https://images.asics.com/is/image/asics/1201A505_103_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1201A505", "Url": "https://www.asics.com/us/en-us/tiger-runner/p/ANA_1201A505-103.html"}
{"Title": "GEL-LYTE V MODERN PATCHWORK", "Onsale": "New", "Price": "$130.00", "Width": "Standard", "Product Category": "Men's Sportstyle Shoes", "Current Color": "Midnight/Ivy", "Deal link": "", "Coming soon?": "\n        GEL-LYTE V MODERN PATCHWORK\n    ", "Image link": "https://images.asics.com/is/image/asics/1201A823_400_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1201A823", "Url": "https://www.asics.com/us/en-us/gel-lyte-v-modern-patchwork/p/ANA_1201A823-400.html"}
{"Title": "GEL-LYTE V MODERN PATCHWORK", "Onsale": "New", "Price": "$130.00", "Width": "Standard", "Product Category": "Men's Sportstyle Shoes", "Current Color": "Caravan/Black", "Deal link": "", "Coming soon?": "\n        GEL-LYTE V MODERN PATCHWORK\n    ", "Image link": "https://images.asics.com/is/image/asics/1201A884_200_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1201A884", "Url": "https://www.asics.com/us/en-us/gel-lyte-v-modern-patchwork/p/ANA_1201A884-200.html"}
{"Title": "GEL-QUANTUM 360 VII", "Onsale": "Not on sale", "Price": "$160.00", "Width": "Standard", "Product Category": "Men's Sportstyle Shoes", "Current Color": "White/White", "Deal link": "Advanced cushioning and technologies for everyday scenarios.", "Coming soon?": "\n        GEL-QUANTUM 360 VII\n    ", "Image link": "https://images.asics.com/is/image/asics/1201A481_100_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1201A481", "Url": "https://www.asics.com/us/en-us/gel-quantum-360-vii/p/ANA_1201A481-100.html"}
{"Title": "GEL-QUANTUM 360 VII", "Onsale": "Not on sale", "Price": "$160.00", "Width": "Standard", "Product Category": "Men's Sportstyle Shoes", "Current Color": "Sour Yuzu/Black", "Deal link": "Advanced cushioning and technologies for everyday scenarios.", "Coming soon?": "\n        GEL-QUANTUM 360 VII\n    ", "Image link": "https://images.asics.com/is/image/asics/1201A481_750_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1201A481", "Url": "https://www.asics.com/us/en-us/gel-quantum-360-vii/p/ANA_1201A481-750.html"}
{"Title": "GEL-QUANTUM 360 VII", "Onsale": "Not on sale", "Price": "$160.00", "Width": "Standard", "Product Category": "Men's Sportstyle Shoes", "Current Color": "Black/Red Alert", "Deal link": "Advanced cushioning and technologies for everyday scenarios.", "Coming soon?": "\n        GEL-QUANTUM 360 VII\n    ", "Image link": "https://images.asics.com/is/image/asics/1201A481_004_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1201A481", "Url": "https://www.asics.com/us/en-us/gel-quantum-360-vii/p/ANA_1201A481-004.html"}
{"Title": "GEL-LYTE III", "Onsale": "Not on sale", "Price": "$130.00", "Width": "Standard", "Product Category": "Men's Sportstyle Shoes", "Current Color": "Feather Grey/Feather Grey", "Deal link": "", "Coming soon?": "\n        GEL-LYTE III\n    ", "Image link": "https://images.asics.com/is/image/asics/1201A050_022_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1201A050", "Url": "https://www.asics.com/us/en-us/gel-lyte-iii/p/ANA_1201A050-022.html"}
{"Title": "GEL-LYTE III", "Onsale": "Not on sale", "Price": "$130.00", "Width": "Standard", "Product Category": "Men's Sportstyle Shoes", "Current Color": "Obsidian Grey/Obsidian Grey", "Deal link": "", "Coming soon?": "\n        GEL-LYTE III\n    ", "Image link": "https://images.asics.com/is/image/asics/1201A050_023_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1201A050", "Url": "https://www.asics.com/us/en-us/gel-lyte-iii/p/ANA_1201A050-023.html"}
{"Title": "GEL-SONOMA 15-50", "Onsale": "Sale", "Price": "$99.95", "Width": "Standard", "Product Category": "Men's Sportstyle Shoes", "Current Color": "Oyster Grey/Cream", "Deal link": "", "Coming soon?": "\n        GEL-SONOMA 15-50\n    ", "Image link": "https://images.asics.com/is/image/asics/1201A714_020_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1201A714", "Url": "https://www.asics.com/us/en-us/gel-sonoma-15-50/p/ANA_1201A714-020.html"}
