{"Title": "FujiSpeed", "Onsale": "Sale", "Price": "$109.95", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Papaya/Indigo Blue", "Deal link": "", "Coming soon?": "\n        FujiSpeed\n    ", "Image link": "https://images.asics.com/is/image/asics/1012B176_700_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012B176", "Url": "https://www.asics.com/us/en-us/fujispeed/p/ANA_1012B176-700.html"}
{"Title": "GEL-VENTURE 7", "Onsale": "Sale", "Price": "$39.95", "Width": "Wide", "Product Category": "Women's Trail Running Shoes", "Current Color": "Steel Grey/Glacier Grey", "Deal link": "", "Coming soon?": "\n        GEL-VENTURE 7\n    ", "Image link": "https://images.asics.com/is/image/asics/1012B110_020_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012B110", "Url": "https://www.asics.com/us/en-us/gel-venture-7/p/ANA_1012B110-020.html"}
{"Title": "GEL-Trabuco Terra", "Onsale": "Not on sale", "Price": "$110.00", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Indigo Blue/Sandstorm", "Deal link": "", "Coming soon?": "\n        GEL-Trabuco Terra\n    ", "Image link": "https://images.asics.com/is/image/asics/1012A902_410_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012A902", "Url": "https://www.asics.com/us/en-us/gel-trabuco-terra/p/ANA_1012A902-410.html"}
{"Title": "Fuji Lite 3", "Onsale": "New", "Price": "$120.00", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Ink Teal/Digital Violet", "Deal link": "", "Coming soon?": "\n        Fuji Lite 3\n    ", "Image link": "https://images.asics.com/is/image/asics/1012B294_400_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012B294", "Url": "https://www.asics.com/us/en-us/fuji-lite-3/p/ANA_1012B294-400.html"}
{"Title": "Fuji Lite 3", "Onsale": "New", "Price": "$120.00", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Papaya/Light Sage", "Deal link": "", "Coming soon?": "\n        Fuji Lite 3\n    ", "Image link": "https://images.asics.com/is/image/asics/1012B294_700_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012B294", "Url": "https://www.asics.com/us/en-us/fuji-lite-3/p/ANA_1012B294-700.html"}
{"Title": "TRAIL SCOUT 2", "Onsale": "Sale", "Price": "$49.95", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Indigo Blue/Light Sage", "Deal link": "", "Coming soon?": "\n        TRAIL SCOUT 2\n    ", "Image link": "https://images.asics.com/is/image/asics/1012B039_405_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012B039", "Url": "https://www.asics.com/us/en-us/trail-scout-2/p/ANA_1012B039-405.html"}
{"Title": "TRAIL SCOUT 2", "Onsale": "Sale", "Price": "$49.95", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Sheet Rock/Papaya", "Deal link": "", "Coming soon?": "\n        TRAIL SCOUT 2\n    ", "Image link": "https://images.asics.com/is/image/asics/1012B039_022_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012B039", "Url": "https://www.asics.com/us/en-us/trail-scout-2/p/ANA_1012B039-022.html"}
{"Title": "TRAIL SCOUT 2", "Onsale": "Sale", "Price": "$49.95", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Black/Whisper Green", "Deal link": "", "Coming soon?": "\n        TRAIL SCOUT 2\n    ", "Image link": "https://images.asics.com/is/image/asics/1012B039_010_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012B039", "Url": "https://www.asics.com/us/en-us/trail-scout-2/p/ANA_1012B039-010.html"}
{"Title": "GEL-VENTURE 7", "Onsale": "Sale", "Price": "$39.95", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Steel Grey/Glacier Grey", "Deal link": "", "Coming soon?": "\n        GEL-VENTURE 7\n    ", "Image link": "https://images.asics.com/is/image/asics/1012B109_020_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012B109", "Url": "https://www.asics.com/us/en-us/gel-venture-7/p/ANA_1012B109-020.html"}
{"Title": "Fuji Lite 3", "Onsale": "Not on sale", "Price": "$120.00", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Night Shade/Nova Orange", "Deal link": "", "Coming soon?": "\n        Fuji Lite 3\n    ", "Image link": "https://images.asics.com/is/image/asics/1012B294_500_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012B294", "Url": "https://www.asics.com/us/en-us/fuji-lite-3/p/ANA_1012B294-500.html"}
{"Title": "GEL-VENTURE 8", "Onsale": "Sale", "Price": "$54.95", "Width": "Standard", "Product Category": "Women's Trail Running Shoes", "Current Color": "Black/Orchid", "Deal link": "", "Coming soon?": "\n        GEL-VENTURE 8\n    ", "Image link": "https://images.asics.com/is/image/asics/1012A708_901_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012A708", "Url": "https://www.asics.com/us/en-us/gel-venture-8/p/ANA_1012A708-901.html"}
{"Title": "GEL-VENTURE 7 (D)", "Onsale": "Sale", "Price": "$39.95", "Width": "Wide", "Product Category": "Women's Trail Running Shoes", "Current Color": "Sheet Rock/Ice Mint", "Deal link": "", "Coming soon?": "\n        GEL-VENTURE 7 (D)\n    ", "Image link": "https://images.asics.com/is/image/asics/1012A477_024_SR_RT_GLB-1?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1012A477", "Url": "https://www.asics.com/us/en-us/gel-venture-7-d/p/ANA_1012A477-024.html"}
