{"Title": "SOLUTION SWIFT FF CLAY", "Onsale": "New", "Price": "$110.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        SOLUTION SWIFT FF CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A198_105_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A198", "Url": "https://www.asics.com/us/en-us/solution-swift-ff-clay/p/ANA_1042A198-105.html"}
{"Title": "GEL-DEDICATE 6", "Onsale": "Sale", "Price": "$59.95", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Silver", "Deal link": "", "Coming soon?": "\n        GEL-DEDICATE 6\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A067_101_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A067", "Url": "https://www.asics.com/us/en-us/gel-dedicate-6/p/ANA_1042A067-101.html"}
{"Title": "SOLUTION SPEED FF 2", "Onsale": "Not on sale", "Price": "$140.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Black", "Deal link": "", "Coming soon?": "\n        SOLUTION SPEED FF 2\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A136_100_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A136", "Url": "https://www.asics.com/us/en-us/solution-speed-ff-2/p/ANA_1042A136-100.html"}
{"Title": "COURT FF 3", "Onsale": "New", "Price": "$170.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Pure Silver", "Deal link": "", "Coming soon?": "\n        COURT FF 3\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A220_100_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A220", "Url": "https://www.asics.com/us/en-us/court-ff-3/p/ANA_1042A220-100.html"}
{"Title": "GEL-GAME 9 CLAY/OC", "Onsale": "New", "Price": "$90.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "Sky/Reborn Blue", "Deal link": "OneASICS\u2122 members save 15% on NAGINO\u2122 clothing styles (no code required) or save 25% on NAGINO\u2122 clothing when purchased along with NAGINO\u2122 footwear.\u00a0 \u00a0*Terms apply.", "Coming soon?": "\n        GEL-GAME 9 CLAY/OC\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A217_400_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A217", "Url": "https://www.asics.com/us/en-us/gel-game-9-clayoc/p/ANA_1042A217-400.html"}
{"Title": "SOLUTION SPEED FF 2 OC", "Onsale": "New", "Price": "$140.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        SOLUTION SPEED FF 2 OC\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A135_104_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A135", "Url": "https://www.asics.com/us/en-us/solution-speed-ff-2-oc/p/ANA_1042A135-104.html"}
{"Title": "SOLUTION SPEED FF 2 CLAY", "Onsale": "New", "Price": "$140.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        SOLUTION SPEED FF 2 CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A134_104_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A134", "Url": "https://www.asics.com/us/en-us/solution-speed-ff-2-clay/p/ANA_1042A134-104.html"}
{"Title": "GEL-CHALLENGER 13 CLAY", "Onsale": "New", "Price": "$100.00", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        GEL-CHALLENGER 13 CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A165_104_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A165", "Url": "https://www.asics.com/us/en-us/gel-challenger-13-clay/p/ANA_1042A165-104.html"}
{"Title": "GEL-DEDICATE 7 CLAY", "Onsale": "New", "Price": "$80.00", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        GEL-DEDICATE 7 CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A168_104_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A168", "Url": "https://www.asics.com/us/en-us/gel-dedicate-7-clay/p/ANA_1042A168-104.html"}
{"Title": "SOLUTION SWIFT FF CLAY", "Onsale": "New", "Price": "$110.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "Sky/Reborn Blue", "Deal link": "OneASICS\u2122 members save 15% on NAGINO\u2122 clothing styles (no code required) or save 25% on NAGINO\u2122 clothing when purchased along with NAGINO\u2122 footwear.\u00a0 \u00a0*Terms apply.", "Coming soon?": "\n        SOLUTION SWIFT FF CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A198_401_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A198", "Url": "https://www.asics.com/us/en-us/solution-swift-ff-clay/p/ANA_1042A198-401.html"}
{"Title": "GEL-GAME 9", "Onsale": "New", "Price": "$90.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        GEL-GAME 9\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A211_101_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A211", "Url": "https://www.asics.com/us/en-us/gel-game-9/p/ANA_1042A211-101.html"}
{"Title": "GEL-RESOLUTION 9 OC", "Onsale": "New", "Price": "$150.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        GEL-RESOLUTION 9 OC\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A225_101_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A225", "Url": "https://www.asics.com/us/en-us/gel-resolution-9-oc/p/ANA_1042A225-101.html"}
{"Title": "GEL-DEDICATE 7 CLAY", "Onsale": "New", "Price": "$80.00", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "Sky/White", "Deal link": "OneASICS\u2122 members save 15% on NAGINO\u2122 clothing styles (no code required) or save 25% on NAGINO\u2122 clothing when purchased along with NAGINO\u2122 footwear.\u00a0 \u00a0*Terms apply.", "Coming soon?": "\n        GEL-DEDICATE 7 CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A168_405_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A168", "Url": "https://www.asics.com/us/en-us/gel-dedicate-7-clay/p/ANA_1042A168-405.html"}
{"Title": "GEL-DEDICATE 7", "Onsale": "New", "Price": "$80.00", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        GEL-DEDICATE 7\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A167_104_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A167", "Url": "https://www.asics.com/us/en-us/gel-dedicate-7/p/ANA_1042A167-104.html"}
{"Title": "SOLUTION SWIFT FF", "Onsale": "New", "Price": "$110.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        SOLUTION SWIFT FF\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A197_105_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A197", "Url": "https://www.asics.com/us/en-us/solution-swift-ff/p/ANA_1042A197-105.html"}
{"Title": "GEL-CHALLENGER 13 CLAY", "Onsale": "New", "Price": "$100.00", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "Sky/Reborn Blue", "Deal link": "OneASICS\u2122 members save 15% on NAGINO\u2122 clothing styles (no code required) or save 25% on NAGINO\u2122 clothing when purchased along with NAGINO\u2122 footwear.\u00a0 \u00a0*Terms apply.", "Coming soon?": "\n        GEL-CHALLENGER 13 CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A165_404_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A165", "Url": "https://www.asics.com/us/en-us/gel-challenger-13-clay/p/ANA_1042A165-404.html"}
{"Title": "GEL-DEDICATE 7", "Onsale": "New", "Price": "$80.00", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "Sky/White", "Deal link": "OneASICS\u2122 members save 15% on NAGINO\u2122 clothing styles (no code required) or save 25% on NAGINO\u2122 clothing when purchased along with NAGINO\u2122 footwear.\u00a0 \u00a0*Terms apply.", "Coming soon?": "\n        GEL-DEDICATE 7\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A167_405_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A167", "Url": "https://www.asics.com/us/en-us/gel-dedicate-7/p/ANA_1042A167-405.html"}
{"Title": "SOLUTION SWIFT FF", "Onsale": "New", "Price": "$110.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "Sky/Reborn Blue", "Deal link": "OneASICS\u2122 members save 15% on NAGINO\u2122 clothing styles (no code required) or save 25% on NAGINO\u2122 clothing when purchased along with NAGINO\u2122 footwear.\u00a0 \u00a0*Terms apply.", "Coming soon?": "\n        SOLUTION SWIFT FF\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A197_401_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A197", "Url": "https://www.asics.com/us/en-us/solution-swift-ff/p/ANA_1042A197-401.html"}
{"Title": "GEL-CHALLENGER 13", "Onsale": "New", "Price": "$100.00", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        GEL-CHALLENGER 13\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A164_104_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A164", "Url": "https://www.asics.com/us/en-us/gel-challenger-13/p/ANA_1042A164-104.html"}
{"Title": "GEL-RESOLUTION 9 CLAY", "Onsale": "New", "Price": "$150.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        GEL-RESOLUTION 9 CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A224_101_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A224", "Url": "https://www.asics.com/us/en-us/gel-resolution-9-clay/p/ANA_1042A224-101.html"}
{"Title": "GEL-GAME 9", "Onsale": "New", "Price": "$90.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "Sky/Reborn Blue", "Deal link": "OneASICS\u2122 members save 15% on NAGINO\u2122 clothing styles (no code required) or save 25% on NAGINO\u2122 clothing when purchased along with NAGINO\u2122 footwear.\u00a0 \u00a0*Terms apply.", "Coming soon?": "\n        GEL-GAME 9\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A211_400_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A211", "Url": "https://www.asics.com/us/en-us/gel-game-9/p/ANA_1042A211-400.html"}
{"Title": "GEL-RESOLUTION 9 CLAY", "Onsale": "New", "Price": "$150.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Pure Silver", "Deal link": "", "Coming soon?": "\n        GEL-RESOLUTION 9 CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A224_100_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A224", "Url": "https://www.asics.com/us/en-us/gel-resolution-9-clay/p/ANA_1042A224-100.html"}
{"Title": "GEL-RESOLUTION 9", "Onsale": "New", "Price": "$150.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        GEL-RESOLUTION 9\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A208_101_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A208", "Url": "https://www.asics.com/us/en-us/gel-resolution-9/p/ANA_1042A208-101.html"}
{"Title": "GEL-GAME 9", "Onsale": "New", "Price": "$90.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Pure Silver", "Deal link": "", "Coming soon?": "\n        GEL-GAME 9\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A211_100_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A211", "Url": "https://www.asics.com/us/en-us/gel-game-9/p/ANA_1042A211-100.html"}
{"Title": "GEL-RESOLUTION 9", "Onsale": "New", "Price": "$150.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Pure Silver", "Deal link": "", "Coming soon?": "\n        GEL-RESOLUTION 9\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A208_100_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A208", "Url": "https://www.asics.com/us/en-us/gel-resolution-9/p/ANA_1042A208-100.html"}
{"Title": "COURT FF 3 CLAY", "Onsale": "New", "Price": "$170.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        COURT FF 3 CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A221_101_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A221", "Url": "https://www.asics.com/us/en-us/court-ff-3-clay/p/ANA_1042A221-101.html"}
{"Title": "SOLUTION SPEED FF 2", "Onsale": "New", "Price": "$140.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        SOLUTION SPEED FF 2\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A136_104_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A136", "Url": "https://www.asics.com/us/en-us/solution-speed-ff-2/p/ANA_1042A136-104.html"}
{"Title": "COURT FF 3", "Onsale": "New", "Price": "$170.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "White/Amethyst", "Deal link": "", "Coming soon?": "\n        COURT FF 3\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A220_101_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A220", "Url": "https://www.asics.com/us/en-us/court-ff-3/p/ANA_1042A220-101.html"}
{"Title": "SOLUTION SPEED FF 2", "Onsale": "New", "Price": "$130.00", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "Black/White", "Deal link": "", "Coming soon?": "\n        SOLUTION SPEED FF 2\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A136_001_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A136", "Url": "https://www.asics.com/us/en-us/solution-speed-ff-2/p/ANA_1042A136-001.html"}
{"Title": "GEL-CHALLENGER 13", "Onsale": "New", "Price": "$100.00", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "Sky/Reborn Blue", "Deal link": "OneASICS\u2122 members save 15% on NAGINO\u2122 clothing styles (no code required) or save 25% on NAGINO\u2122 clothing when purchased along with NAGINO\u2122 footwear.\u00a0 \u00a0*Terms apply.", "Coming soon?": "\n        GEL-CHALLENGER 13\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A164_404_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A164", "Url": "https://www.asics.com/us/en-us/gel-challenger-13/p/ANA_1042A164-404.html"}
{"Title": "SOLUTION SWIFT FF", "Onsale": "Sale", "Price": "$74.95", "Width": "Standard", "Product Category": "Women's Tennis Shoes", "Current Color": "Frosted Rose/Cranberry", "Deal link": "", "Coming soon?": "\n        SOLUTION SWIFT FF\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A197_700_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A197", "Url": "https://www.asics.com/us/en-us/solution-swift-ff/p/ANA_1042A197-700.html"}
{"Title": "GEL-CHALLENGER 13 CLAY", "Onsale": "Sale", "Price": "$79.95", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "White/Cranberry", "Deal link": "", "Coming soon?": "\n        GEL-CHALLENGER 13 CLAY\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A165_103_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A165", "Url": "https://www.asics.com/us/en-us/gel-challenger-13-clay/p/ANA_1042A165-103.html"}
{"Title": "GEL-CHALLENGER 13", "Onsale": "Sale", "Price": "$69.95", "Width": null, "Product Category": "Women's Tennis Shoes", "Current Color": "White/Cranberry", "Deal link": "", "Coming soon?": "\n        GEL-CHALLENGER 13\n    ", "Image link": "https://images.asics.com/is/image/asics/1042A164_103_SR_RT_GLB?$sfcc-product$&fmt=jpg&wid=683&hei=512", "Style": "1042A164", "Url": "https://www.asics.com/us/en-us/gel-challenger-13/p/ANA_1042A164-103.html"}
